version: '3.9'

networks:
  panda-net:
    driver: bridge

services:

  panda-frontend:
    container_name: panda-frontend
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      labels: 
        - panda-frontend
    networks:
      - panda-net        
    ports:
      - '127.0.0.1:5000:80'
