version: '3.9'

networks:
  panda-net:
    driver: bridge
    name: panda-net

services:
  panda-frontend-ui-main-app:
    container_name: panda-frontend-ui-main-app
    restart: unless-stopped
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - MINIO_ACCESS_KEY_PROD=${MINIO_ACCESS_KEY_PROD}
      - MINIO_SECRET_KEY_PROD=${MINIO_SECRET_KEY_PROD}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - AZURE_AD_BEAMLINES_CLIENT_ID=${AZURE_AD_BEAMLINES_CLIENT_ID}
      - AZURE_AD_BEAMLINES_CLIENT_SECRET=${AZURE_AD_BEAMLINES_CLIENT_SECRET}
      - AZURE_AD_BEAMLINES_TENANT_ID=${AZURE_AD_BEAMLINES_TENANT_ID}
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - panda-frontend-ui-main-app
      args:
        - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    networks:
      - panda-net
    ports:
      - '127.0.0.1:5000:5001'
