# Stage 1: Build Stage
FROM node:18-alpine AS builder

# Install build tools and dependencies required to compile sharp
RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    vips-dev

WORKDIR /app

# Copy package files and install dependencies
COPY package.json yarn.lock ./

# Set environment variables to build sharp from source
ENV npm_config_platform=linuxmusl \
    npm_config_build_from_source=true

# Install all dependencies, including devDependencies
RUN yarn install --frozen-lockfile

# Copy the rest of the application's source code
COPY . .

# Set build-time environment variables (ARG)
ARG NEO4J_PASSWORD
ARG AZURE_AD_BEAMLINES_CLIENT_ID
ARG AZURE_AD_BEAMLINES_CLIENT_SECRET
ARG AZURE_AD_BEAMLINES_TENANT_ID
ARG NEXT_SHARP_PATH

# Set environment variables for the build stage
ENV PANDA_API_GW_URL="https://api-dev.panda.eli-beams.eu/v1" \
    PANDA_ENV="dev" \
    MINIO_ENDPOINT="minio-main" \
    MINIO_BUCKET_NAME="panda-dev" \
    NEO4J_USER="neo4j" \
    NEO4J_URI="bolt://panda-neo4j-dev:7687" \
    NEO4J_PASSWORD="${NEO4J_PASSWORD}" \
    AZURE_AD_BEAMLINES_CLIENT_ID="${AZURE_AD_BEAMLINES_CLIENT_ID}" \
    AZURE_AD_BEAMLINES_CLIENT_SECRET="${AZURE_AD_BEAMLINES_CLIENT_SECRET}" \
    AZURE_AD_BEAMLINES_TENANT_ID="${AZURE_AD_BEAMLINES_TENANT_ID}" \
    NEXT_SHARP_PATH="${NEXT_SHARP_PATH}"

# Build the application
RUN yarn build

# Stage 2: Production Stage
FROM node:18-alpine AS runner

WORKDIR /app

# Install runtime dependencies
RUN apk add --no-cache \
    libc6-compat \
    vips

# Set environment variables for the production stage
ENV NODE_ENV="production" \
    PANDA_API_GW_URL="https://api-dev.panda.eli-beams.eu/v1" \
    NEXTAUTH_URL="https://dev.panda.eli-beams.eu/" \
    PANDA_ENV="dev" \
    MINIO_ENDPOINT="minio-main" \
    MINIO_BUCKET_NAME="panda-dev" \
    NEO4J_USER="neo4j" \
    NEO4J_URI="bolt://panda-neo4j-dev:7687" \
    NEO4J_PASSWORD="${NEO4J_PASSWORD}" \
    AZURE_AD_BEAMLINES_CLIENT_ID="${AZURE_AD_BEAMLINES_CLIENT_ID}" \
    AZURE_AD_BEAMLINES_CLIENT_SECRET="${AZURE_AD_BEAMLINES_CLIENT_SECRET}" \
    AZURE_AD_BEAMLINES_TENANT_ID="${AZURE_AD_BEAMLINES_TENANT_ID}" \
    NEXT_SHARP_PATH="${NEXT_SHARP_PATH}"

# Copy the built application and necessary files
COPY --from=builder /app/.next/ ./.next/
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/package.json ./

# Copy the production node_modules from the builder
COPY --from=builder /app/node_modules ./node_modules

# Remove development dependencies
RUN yarn install --production --ignore-scripts --prefer-offline

# Remove unnecessary files to reduce image size
RUN rm -rf /var/cache/apk/* /tmp/*

# Create non-root user and set permissions
RUN addgroup -S nodejs && \
    adduser -S nextjs -G nodejs && \
    chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 5001
ENV PORT 5001

# Start the application
CMD ["node", ".next/standalone/server.js"]