# 1. Install dependencies only when needed
FROM node:18-alpine AS deps

# Install build tools and dependencies
RUN apk add --no-cache \
    libc6-compat \
    python3 \
    make \
    g++ \
    vips-dev \
    autoconf \
    automake \
    libtool \
    pkgconfig

WORKDIR /app

# Install dependencies with build flags
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
    if [ -f yarn.lock ]; then npm_config_build_from_source=true yarn install --frozen-lockfile; \
    elif [ -f package-lock.json ]; then npm_config_build_from_source=true npm ci; \
    elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm && npm_config_build_from_source=true pnpm install; \
    else echo "Lockfile not found." && exit 1; \
    fi

# 2. Rebuild the source code only when needed
FROM node:18-alpine AS builder

# Copy build tools
RUN apk add --no-cache \
    libc6-compat \
    python3 \
    make \
    g++ \
    vips-dev \
    autoconf \
    automake \
    libtool \
    pkgconfig

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Set environment variables
ARG NEO4J_PASSWORD

ENV PANDA_API_GW_URL="https://api-dev.panda.eli-beams.eu/v1"
ENV PANDA_ENV="dev"
ENV MINIO_ENDPOINT="minio-main"
ENV MINIO_BUCKET_NAME="panda-dev"
ENV NEO4J_USER="neo4j"
ENV NEO4J_URI="bolt://panda-neo4j-dev:7687"
ENV NEO4J_PASSWORD="${NEO4J_PASSWORD}"
ENV AZURE_AD_BEAMLINES_CLIENT_ID="${AZURE_AD_BEAMLINES_CLIENT_ID}"
ENV AZURE_AD_BEAMLINES_CLIENT_SECRET="${AZURE_AD_BEAMLINES_CLIENT_SECRET}"
ENV AZURE_AD_BEAMLINES_TENANT_ID="${AZURE_AD_BEAMLINES_TENANT_ID}"
ENV NEXT_SHARP_PATH="${NEXT_SHARP_PATH}"

# Build the application
RUN yarn build

# 3. Production image, copy all the files and run next
FROM node:18-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

# Copy environment variables
ENV PANDA_API_GW_URL="https://api-dev.panda.eli-beams.eu/v1"
ENV NEXTAUTH_URL="https://dev.panda.eli-beams.eu/"
ENV PANDA_ENV="dev"
ENV MINIO_ENDPOINT="minio-main"
ENV MINIO_BUCKET_NAME="panda-dev"
ENV NEO4J_USER="neo4j"
ENV NEO4J_URI="bolt://panda-neo4j-dev:7687"
ENV NEO4J_PASSWORD="${NEO4J_PASSWORD}"
ENV AZURE_AD_BEAMLINES_CLIENT_ID="${AZURE_AD_BEAMLINES_CLIENT_ID}"
ENV AZURE_AD_BEAMLINES_CLIENT_SECRET="${AZURE_AD_BEAMLINES_CLIENT_SECRET}"
ENV AZURE_AD_BEAMLINES_TENANT_ID="${AZURE_AD_BEAMLINES_TENANT_ID}"
ENV NEXT_SHARP_PATH="${NEXT_SHARP_PATH}"

# Install libc6-compat for runtime
RUN apk add --no-cache libc6-compat

# Create non-root user
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

# Copy necessary files
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Set user and expose port
USER nextjs
EXPOSE 5001
ENV PORT 5001

# Start the application
CMD ["node", "server.js"]
