# 1. Install dependencies only when needed
FROM node:18-alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
    elif [ -f package-lock.json ]; then npm ci; \
    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
    else echo "Lockfile not found." && exit 1; \
    fi


# 2. Rebuild the source code only when needed
FROM node:18-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEO4J_PASSWORD


ENV PANDA_API_GW_URL="https://api-test.panda.eli-beams.eu/v1"
ENV PANDA_ENV="test"
ENV MINIO_ENDPOINT="minio-main"
ENV MINIO_BUCKET_NAME="panda-test"
ENV NEO4J_USER="neo4j"
ENV NEO4J_URI="bolt://panda-neo4j-test:7687"
ENV NEO4J_PASSWORD="${NEO4J_PASSWORD}"
ENV AZURE_AD_BEAMLINES_CLIENT_ID="${AZURE_AD_BEAMLINES_CLIENT_ID}"
ENV AZURE_AD_BEAMLINES_CLIENT_SECRET="${AZURE_AD_BEAMLINES_CLIENT_SECRET}"
ENV AZURE_AD_BEAMLINES_TENANT_ID="${AZURE_AD_BEAMLINES_TENANT_ID}"
ENV NEXT_SHARP_PATH="${NEXT_SHARP_PATH}"

# This will do the trick, use the corresponding env file for each environment.
# COPY .env.production.sample .env.production
RUN yarn build

# 3. Production image, copy all the files and run next
FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PANDA_API_GW_URL="https://api-test.panda.eli-beams.eu/v1"
ENV NEXTAUTH_URL="https://test.panda.eli-beams.eu/"
ENV PANDA_ENV="test"
ENV MINIO_ENDPOINT="minio-main"
ENV MINIO_BUCKET_NAME="panda-test"
ENV NEO4J_USER="neo4j"
ENV NEO4J_URI="bolt://panda-neo4j-test:7687"
ENV NEO4J_PASSWORD="${NEO4J_PASSWORD}"
ENV AZURE_AD_BEAMLINES_CLIENT_ID="${AZURE_AD_BEAMLINES_CLIENT_ID}"
ENV AZURE_AD_BEAMLINES_CLIENT_SECRET="${AZURE_AD_BEAMLINES_CLIENT_SECRET}"
ENV AZURE_AD_BEAMLINES_TENANT_ID="${AZURE_AD_BEAMLINES_TENANT_ID}"
ENV NEXT_SHARP_PATH="${NEXT_SHARP_PATH}"

RUN env


RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# Ensure Sharp is copied to the production container
COPY --from=builder /app/node_modules ./node_modules


USER nextjs

EXPOSE 5001

ENV PORT 5001

CMD ["node", "server.js"]
