openapi: 3.0.2
info:
  title: PANDA API Gateway
  description: This is an API Gateway to the PANDA database. This is the only place to access data from the PANDA database.
  version: '0.1'
  contact:
    name: Jiří Švácha
    email: jiri.svacha@eli-beams.eu
paths:
  /authenticate:
    get:
      description: Get user data based on JWT token in the authentication Bearer header.    
      security:
        - jwtAuth: []   
      tags:
        - Security
      responses:
        '200':
          description: Returns authenticated user data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticatedUser"
    post:
      description: Authenticate user by username and password and return JWT token.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/LoginForm"
      tags:
        - Security
      responses:
        '200':
          description: Returns JWT token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
  /system:    
    post:
      description: Create new standalone system and return its new identifier(id)
      security:
        - jwtAuth: []      
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/NewSystemForm"
      tags:
        - Systems
      responses:
        '200':
          description: Returns new System id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewID"

components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Token:
      type: object
      description: Represent JWT token
      properties:
        access_token:
          type: string
    NewID:
      type: object
      description: Typicaly if we create new object we return new object id
      properties:
        id:
          type: integer
          format: int64          
    NewSystemForm:
      type: object
      description: Object to create new System
      properties:
        name:
          type: string          
        description:
          type: string
        systemCode:
          type: string
        systemAlias:
          type: string
        facilityZone:
          type: string
        location:
          type: string
        ownerPerson:
          type: string
        responsiblePerson:
          type: string
        maintainedByPerson:
          type: string
      required:
        - name
    UpdateSystemForm:
      type: object
      description: Object to update existing System
      properties:
        name:
          type: string          
        description:
          type: string
        systemCode:
          type: string
        systemAlias:
          type: string
        facilityZone:
          type: string
        location:
          type: string
        ownerPerson:
          type: string
        responsiblePerson:
          type: string
        maintainedByPerson:
          type: string      
    LoginForm:
      type: object
      description: Object to authenticate user
      properties:
        username:
          type: string          
        password:
          type: string
      required: [username, password]
    AuthenticatedUser:
      type: object
      description: Information about user authenticated via JWT token
      properties:
        displayName:
          type: string          
        id:
          type: integer
          format: int64
        email:
          type: string
        role:
          type: array
          items:
            type: string       