version: '3.9'

networks:
  panda-net:
    driver: bridge
    name: panda-net

services:
  panda-ui-main-app-test:
    container_name: panda-ui-main-app-cypress
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - panda-ui-main-app-cypress
    networks:
      - panda-net
    ports:
      - '127.0.0.1:5555:5001'
  panda-ui-main-app-cypress:
    container_name: panda-ui-main-app-cypress
    restart: "no"
    image: cypress/included:11.1.0@sha256:463346f660d0e471c995cb8c419a3aed22afb00afa9f7aaf4e3f72908493d108
    volumes:
      - "$PWD:/e2e"   
    working_dir: "/e2e"
    networks:
      - panda-net
    ports:
      - '127.0.0.1:5555:5001'
    depends_on:
      - panda-ui-main-app-test