import { setCookies } from './auth.cy'
import { SCRENARIOS, setApiMocks } from './shared'
//TODO!
beforeEach(() => {
  cy.clearLocalStorage()
  cy.clearCookies()
})

describe.only('Catalogue', () => {
  it('Catalogue', () => {
    setApiMocks(SCRENARIOS.customSession.session(true))
    cy.visit(Cypress.env('host') + '/catalogue')
    cy.wait(['@session'])
    setCookies()
    cy.visit(Cypress.env('host') + '/catalogue')
    cy.url().should('include', 'catalogue')
    cy.wait(['@session'])

    cy.wait(['@catalogueCategories'])
    cy.contains('Motion')
    cy.contains('Vacuum Technology')
    cy.contains('Beam characterization').click()
  })
  it('Catalogue search', () => {
    setApiMocks(SCRENARIOS.customSession.session(true))
    cy.visit(Cypress.env('host') + '/catalogue')
    cy.wait(['@session'])
    setCookies()
    cy.visit(Cypress.env('host') + '/catalogue')
    cy.url().should('include', 'catalogue')
    cy.wait(['@session'])

    cy.wait(['@catalogueCategories'])
    cy.get('input[name=search]').clear().type('axis')
    setApiMocks(SCRENARIOS.customCatalogueItems.catalogueItems(7))
    cy.get('[data-testid="search"]').submit()
    cy.url().should('include', '?search=axis&page=1')
    cy.wait(['@catalogueItems'])
    cy.get('[data-testid="item-list"]').should('exist')
    cy.get('[data-testid="catalogue-paging"]').should('exist')
    cy.contains('Beam characterization').click()
    setApiMocks(SCRENARIOS.customCatalogueItems.catalogueItems(3))
    cy.wait(['@catalogueItems'])
    cy.url().should('include', 'beam-characterization')
    cy.contains('Showing 1 to 3 of 3 results')
    cy.get('[data-testid="catalogue-breadcrump-home"]').click()
    setApiMocks(SCRENARIOS.customCatalogueItems.catalogueItems(3))
    //cy.wait(['@catalogueItems'])
    // cy.get('input[name=search]').clear()
    // cy.get('[data-testid="search"]').submit()
    // cy.get('[data-testid="item-list"]').should('not.exist')
    // cy.get('[data-testid="catalogue-paging"]').should('not.exist')
    // cy.get('input[name=search]').clear().type('blablablabla')
    // setApiMocks(SCRENARIOS.customCatalogueItems.catalogueItems(0))
    // cy.get('[data-testid="search"]').submit()
    // cy.wait(['@catalogueItems'])
    // cy.get('[data-testid="item-list"]').should('exist')
    // cy.get('[data-testid="catalogue-paging"]').should('exist')
    // cy.contains('No results found')
    // cy.contains('Showing 0 to 0 of 0 results')
  })
  it('Item detail', () => {
    setApiMocks(SCRENARIOS.customSession.session(true))
    setCookies()
    cy.visit(Cypress.env('host') + '/catalogue')
    cy.wait(['@session'])
    cy.wait(['@catalogueCategories'])
    cy.get('input[name=search]').clear().type('axis')
    setApiMocks(SCRENARIOS.customCatalogueItems.catalogueItems(1))
    cy.get('[data-testid="search"]').submit()
    cy.contains('ATH 1603 M, DN 200 CF-F').click()
    cy.url().should('include', 'catalogue/item')
    cy.wait(['@catalogueItem'])
    cy.contains('ATH 1603 M, DN 200 CF-F')
    cy.contains('Pumping speed for N2').should('not.exist')
    cy.contains('TMP parameters').click()
    cy.contains('Pumping speed for N2').should('exist')
    cy.get('[data-testid="item-detail-button-back"]').click()
    cy.url().should('not.include', 'catalogue/item')
    cy.url().should('include', 'catalogue')
  })
})
