version: "3.9"
services:
  panda-backend:
    container_name: panda-backend
    restart: unless-stopped
    env_file:
      - /home/svachaj/publish_backend/.env
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - panda-backend
    ports:
      - 127.0.0.1:6969:6969
 


  
