version: '3.9'

services:
  cypress-tests-with-app-inside-container:
    container_name: cypress-tests-with-app-inside-container
    restart: "no"
    environment:
      - CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY}
    build:
      context: ../../
      dockerfile: Dockerfile.cypress-all-in-container
      labels:
        - cypress-tests-with-app-inside-container
