export enum CODEBOOK {
  SYSTEM_TYPE = 'SYSTEM_TYPE',
  SYSTEM_IMPORTANCE = 'SYSTEM_IMPORTANCE',
  SYSTEM_CRITICALITY_CLASS = 'SYSTEM_CRITICALITY_CLASS',
  LOCATION = 'LOCATION',
  ZONE = 'ZONE',
  SUB_ZONE = 'SUB_ZONE',
  ITEM_USAGE = 'ITEM_USAGE',
  ITEM_CONDITION_STATUS = 'ITEM_CONDITION_STATUS',
  USER = 'USER',
  EMPLOYEE = 'EMPLOYEE',
  PROCUREMENTER = 'PROCUREMENTER',
  UNIT = 'UNIT',
  CATALOGUE_PROPERTY_TYPE = 'CATALOGUE_PROPERTY_TYPE',
  SUPPLIER = 'SUPPLIER',
  ORDER_STATUS = 'ORDER_STATUS',

  SYSTEM = 'SYSTEM',
  CATALOGUE_CATEGORY = 'CATALOGUE_CATEGORY',
  MANUFACTURER = 'MANUFACTURER'
}
