export enum PATH {
    ROOT = '/',
    DASHBOARD = '/dashboard',
    CATALOGUE = '/catalogue',
    CATALOGUE_ITEM = '/catalogue/item',
    CATALOGUE_EXPLORER = '/catalogue/explorer',
    SYSTEMS = '/systems/overview',
    SYSTEMS_MOVING = '/systems/moving',
    SYSTEMS_MULTI_MOVE = '/systems/multi-move',
    SYSTEM_RELATIONS = '/systems/relations',
    SYSTEM = '/system',
    SYSTEM_ITEM = '/system/item',
    SYSTEM_TYPE_EDIT = '/system/type-edit',
    SYSTEM_ALIAS = '/system/alias',
    REPORTS = '/reports',
    ORDERS = '/orders',
    ORDER = '/order',
    CODEBOOKS = '/codebooks',
    ROOM_CARDS = '/room-cards',
    ROOM_CARD = '/room-card',
    ADMIN_USERS = '/administration/users',
    ADMIN_USER = '/administration/user',
    ADMIN = '/administration',
    PROFILE_GENERAL = '/profile/general',
    PROFILE_SECURITY = '/profile/security',
    PROFILE_TEAM = '/profile/team',
    LAYOUT = '/layout',
    PUBLICATIONS = '/publications/overview',
    RESEARCHERS = '/publications/researchers',
    GRANTS = '/publications/grants',
    PUBLICATION = '/publication',
    SERVICES = '/services',
    SERVICE = '/service',
    CONTROL_SYSTEMS = '/control-systems/overview',
    CONTROL_SYSTEMS_CREATE = '/control-systems/system-codes-create',
    SYSTEMS_HIERARCHY = '/systems/hierarchy',
    ZONES = '/zones',
    NOT_FOUND = '/404',
}

export const SUPPORT =
    'mailto:panda@eli-laser.eu?subject=Support%20request&body=Please%20describe%20your%20problem%20here.%20Do%20not%20change%20the%20subject,%20please.'
