export enum ROLE {
    CATALOGUE_VIEW = 'catalogue-view',
    SYSTEMS_VIEW = 'systems-view',
    REPORTS_VIEW = 'reports-view',
    BASICS = 'basics',
    SYSTEM_EDIT = 'systems-edit',
    SYSTEM_TYPE_EDIT = 'system-types-edit',
    SYSTEM_TYPE_VIEW = 'system-types-view',
    CATALOGUE_CATEGORY_EDIT = 'catalogue-category-edit',
    CATALOGUE_EDIT = 'catalogue-edit',
    ORDERS_VIEW = 'orders-view',
    ORDERS_EDIT = 'orders-edit',
    ORDERS_DELIVERY_EDIT = 'orders-delivery-edit',
    SUPPLIER_EDIT = 'supplier-edit',
    CODEBOOKS_ADMIN = 'codebooks-admin',
    ROOM_CARD_VIEW = 'room-cards-view',
    ROOM_CARD_EDIT = 'room-cards-edit',
    ADMIN = 'admin',
    DASHBOARD_FILES_ADMIN = 'dashboard-files-admin',
    PUBLICATIONS_VIEW = 'publications-view',
    PUBLICATIONS_EDIT = 'publications-edit',
    SERVICE_VIEW = 'catalogue-service-view',
    SERVICE_EDIT = 'catalogue-service-edit',
    CONTROL_SYSTEMS_VIEW = 'control-systems-view',
    CONTROL_SYSTEMS_EDIT = 'control-systems-edit',
    ZONES_VIEW = 'zones-view',
    ZONES_EDIT = 'zones-edit',
}
