version: '3.9'

networks:
  panda-net:
    name: panda-net
    driver: bridge

services:

  panda-backend:
    container_name: panda-backend
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      labels: 
        - panda-backend
    networks:
      - panda-net
    ports:
      - '127.0.0.1:5001:5001'
