import { SCRENARIOS, setApiMocks } from './panda.shared'

beforeEach(() => {
  cy.clearLocalStorage()
  cy.clearCookies()
})

describe('Catalogue', () => {
  it('Catalogue', () => {
    setApiMocks(SCRENARIOS.signIn.custonSession(true))
    cy.visit(Cypress.env('host') + '/catalogue')
    cy.wait(['@session'])
    cy.url().should('include', 'catalogue')
    cy.wait(['@catalogueCategories'])
    cy.contains('Motion')
    cy.contains('Vacuum Technology')
    cy.contains('Beam characterization').click()
  })
  it.only('Catalogue search', () => {
    setApiMocks(SCRENARIOS.signIn.custonSession(true))
    cy.visit(Cypress.env('host') + '/catalogue')
    cy.wait(['@session'])
    cy.url().should('include', 'catalogue')
    cy.wait(['@catalogueCategories'])
    cy.contains('Beam characterization')
    cy.contains('Motion')
    cy.contains('Vacuum Technology')
    cy.get('input[name=search]').clear().type('axis')
    cy.get('[data-testid="search"]').submit()
    cy.url().should('include', '?search=axis&page=1')
    cy.wait(['@catalogueItems'])
    cy.get('[data-testid="item-list"]').should('exist')
    cy.get('[data-testid="catalogue-paging"]').should('exist')
    cy.contains('Showing 1 to 7 of 7 results')
    cy.contains('ATH 1603 M, DN 200 CF-F')
    cy.contains('ATH 1603 M, DN 250 ISO-F')
    cy.contains('ATH 2303 M, DN 250 ISO-F')
    cy.contains('AXIS M1014')
    cy.contains('AXIS M1045-LW')
    cy.contains('AXIS-PX')
    cy.contains('HiPace 300 M, DN 100, CF-F')
    cy.contains('Cameras').click()
    cy.wait(['@catalogueItems'])
    cy.url().should('include', 'cameras')
    cy.contains('Showing 1 to 3 of 3 results')
    cy.contains('AXIS M1014')
    cy.contains('AXIS M1045-LW')
    cy.contains('AXIS-PX')
    cy.contains('ATH 1603 M, DN 200 CF-F').should('not.exist')
    cy.contains('ATH 1603 M, DN 250 ISO-F').should('not.exist')
    cy.contains('ATH 2303 M, DN 250 ISO-F').should('not.exist')
    cy.contains('HiPace 300 M, DN 100, CF-F').should('not.exist')
    cy.get('[data-testid="catalogue-breadcrump-home"]').click()
    cy.contains('ATH 1603 M, DN 200 CF-F')
    cy.contains('ATH 1603 M, DN 250 ISO-F')
    cy.contains('ATH 2303 M, DN 250 ISO-F')
    cy.contains('AXIS M1014')
    cy.contains('AXIS M1045-LW')
    cy.contains('AXIS-PX')
    cy.contains('HiPace 300 M, DN 100, CF-F')
    cy.get('input[name=search]').clear()
    cy.get('[data-testid="search"]').submit()
    cy.get('[data-testid="item-list"]').should('not.exist')
    cy.get('[data-testid="catalogue-paging"]').should('not.exist')
    cy.get('input[name=search]').clear().type('blablablabla')
    setApiMocks(SCRENARIOS.emptyCatalogueItems)
    cy.get('[data-testid="search"]').submit()
    cy.wait(['@catalogueItems'])
    cy.get('[data-testid="item-list"]').should('exist')
    cy.get('[data-testid="catalogue-paging"]').should('exist')
    cy.contains('No results found')
    cy.contains('Showing 0 to 0 of 0 results')
  })
})

describe('Item', () => {
  it('Item detail', () => {})
})
