version: '3.9'

networks:
  panda-net:
    name: panda-net
    driver: bridge

services:

  panda-backend:
    container_name: panda-microservices-template-service
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - panda-microservices-template-service
    networks:
      - panda-net
    ports:
      - '50055:50055'
