// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: proto/systems-service.proto

package systems_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SystemsServiceClient is the client API for SystemsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemsServiceClient interface {
	DeleteRelationshipByID(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*MessageResponse, error)
}

type systemsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemsServiceClient(cc grpc.ClientConnInterface) SystemsServiceClient {
	return &systemsServiceClient{cc}
}

func (c *systemsServiceClient) DeleteRelationshipByID(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/microservices.SystemsService/DeleteRelationshipByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemsServiceServer is the server API for SystemsService service.
// All implementations must embed UnimplementedSystemsServiceServer
// for forward compatibility
type SystemsServiceServer interface {
	DeleteRelationshipByID(context.Context, *IDRequest) (*MessageResponse, error)
	mustEmbedUnimplementedSystemsServiceServer()
}

// UnimplementedSystemsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSystemsServiceServer struct {
}

func (UnimplementedSystemsServiceServer) DeleteRelationshipByID(context.Context, *IDRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRelationshipByID not implemented")
}
func (UnimplementedSystemsServiceServer) mustEmbedUnimplementedSystemsServiceServer() {}

// UnsafeSystemsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemsServiceServer will
// result in compilation errors.
type UnsafeSystemsServiceServer interface {
	mustEmbedUnimplementedSystemsServiceServer()
}

func RegisterSystemsServiceServer(s grpc.ServiceRegistrar, srv SystemsServiceServer) {
	s.RegisterService(&SystemsService_ServiceDesc, srv)
}

func _SystemsService_DeleteRelationshipByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemsServiceServer).DeleteRelationshipByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microservices.SystemsService/DeleteRelationshipByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemsServiceServer).DeleteRelationshipByID(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemsService_ServiceDesc is the grpc.ServiceDesc for SystemsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microservices.SystemsService",
	HandlerType: (*SystemsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteRelationshipByID",
			Handler:    _SystemsService_DeleteRelationshipByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/systems-service.proto",
}
