name: ci

on:
  pull-request:
    branches:
      - main
  workflow-call:

defaults:
  run:
    working-directory: ./frontend/ui-main-app

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v3

      - name: Use Node 16 🕹️
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: ./frontend/ui-main-app/yarn.lock
          node-version: '16'

      - name: Install ⚙️
        run: yarn install

      - name: Lint 🤓
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v3

      - name: Use Node 16 🕹️
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: ./frontend/ui-main-app/yarn.lock

      - name: Install ⚙️
        run: yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          PANDA_API_GW_URL: ${{ secrets.PANDA_API_GW_URL }}
        with:
          working-directory: ./frontend/ui-main-app
          start: yarn dev
          wait-on: 'http://localhost:5001'
          browser: chrome
