name: Compose docker filebeat-nginx

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: tools/nginx-filebeat

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: copy yml config        
        run: cp $HOME/actions-runner/_work/ELI-panda/ELI-panda/tools/nginx-filebeat/config/filebeat.yml $HOME/nginx-filebeat/filebeat.yml
      - name: Build the Docker compose
        run: docker-compose up -d --build
