name: Compose down backend API GATEWAY

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: backend/api-gateway-go

jobs:
  compose-down:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker compose
        run: docker-compose down
