name: Compose docker neo4j

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: backend/databases/systems

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker compose
        run: docker-compose up -d --build
