name: Compose up DEV frontend on push

on:
  push:
    branches:
      - 'dev'

jobs:
  use-secret:
    runs-on: self-hosted
    steps:
      - name: Show secret stats
        run: |
          echo "${{ secrets.NEXTAUTH_SECRET }}" | "${{ secrets.MINIO_ACCESS_KEY_DEV }}" | "${{ secrets.MINIO_SECRET_KEY_DEV }}" | "${{ secrets.NEO4J_PASSWORD }}" | wc
  compose-up:
    runs-on: self-hosted
    needs: use-secret
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker compose -f docker-compose-dev.yml up -d --build
        env:
          NEXTAUTH_SECRET: '${{ secrets.NEXTAUTH_SECRET }}'
          MINIO_ACCESS_KEY_PROD: '${{ secrets.MINIO_ACCESS_KEY_DEV }}'
          MINIO_SECRET_KEY_PROD: '${{ secrets.MINIO_SECRET_KEY_DEV }}'
          NEO4J_PASSWORD: '${{ secrets.NEO4J_PASSWORD }}'
