name: Compose docker backend

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: backend/api_gateway_py

jobs:
  build:
    runs-on: self-hosted

    steps:
      - run: sudo chown -R $USER:$USER /home/svachaj/actions-runner/_work/
      - uses: actions/checkout@v2
      - name: Build the Docker compose
        run: docker-compose up -d --build
