name: Compose docker Promtail for Loki

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: tools/loki

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker compose
        run: docker-compose up -d --build
