name: Compose up DEV frontend on push

on:
  push:
    branches:
      - 'dev'

jobs:
  use-secret:
    runs-on: self-hosted
    env:
      NEXTAUTH_SECRET: '${{ secrets.NEXTAUTH_SECRET }}'
      MINIO_ACCESS_KEY_PROD: '${{ secrets.MINIO_ACCESS_KEY_DEV }}'
      MINIO_SECRET_KEY_PROD: '${{ secrets.MINIO_SECRET_KEY_DEV }}'
      NEO4J_PASSWORD: '${{ secrets.NEO4J_PASSWORD }}'
      AZURE_AD_BEAMLINES_CLIENT_ID: '${{ secrets.AZURE_AD_BEAMLINES_CLIENT_ID }}'
      AZURE_AD_BEAMLINES_CLIENT_SECRET: '${{ secrets.AZURE_AD_BEAMLINES_CLIENT_SECRET }}'
      AZURE_AD_BEAMLINES_TENANT_ID: '${{ secrets.AZURE_AD_BEAMLINES_TENANT_ID }}'
    steps:
      - name: Show secret stats
        run: |
          echo "${{ secrets.NEXTAUTH_SECRET }}" | "${{ secrets.MINIO_ACCESS_KEY_DEV }}" | "${{ secrets.MINIO_SECRET_KEY_DEV }}" | "${{ secrets.NEO4J_PASSWORD }}" | "${{ secrets.AZURE_AD_BEAMLINES_CLIENT_ID }}" | "${{ secrets.AZURE_AD_BEAMLINES_CLIENT_SECRET }}" | "${{ secrets.AZURE_AD_BEAMLINES_TENANT_ID }}" | wc
  unit-tests:
    runs-on: self-hosted
    needs: use-secret
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Run unit tests
        run: yarn test
  compose-up:
    runs-on: self-hosted
    needs: unit-tests
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker compose -f docker-compose-dev.yml up -d --build
        env:
          NEXTAUTH_SECRET: '${{ secrets.NEXTAUTH_SECRET }}'
          MINIO_ACCESS_KEY_PROD: '${{ secrets.MINIO_ACCESS_KEY_DEV }}'
          MINIO_SECRET_KEY_PROD: '${{ secrets.MINIO_SECRET_KEY_DEV }}'
          NEO4J_PASSWORD: '${{ secrets.NEO4J_PASSWORD }}'
          AZURE_AD_BEAMLINES_CLIENT_ID: '${{ secrets.AZURE_AD_BEAMLINES_CLIENT_ID }}'
          AZURE_AD_BEAMLINES_CLIENT_SECRET: '${{ secrets.AZURE_AD_BEAMLINES_CLIENT_SECRET }}'
          AZURE_AD_BEAMLINES_TENANT_ID: '${{ secrets.AZURE_AD_BEAMLINES_TENANT_ID }}'
