name: Compose microservice catalogue

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: backend/microservices/catalogue-service

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker compose
        run: docker-compose up -d --build
