name: Cypress test on push

on:
  - push

jobs:
  build-run-test:
    runs-on: czechia-server

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Yarn
        run: npm install -g yarn

      - run: yarn install
      - run: yarn build
        env:
          PANDA_API_GW_URL: ${{ env.PANDA_API_GW_URL }}
      - run: yarn start &
      - run: node_modules/cypress/bin/cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --tag "chrome,${{ github.event.head_commit.author.name }},${{ github.event.head_commit.message }}"  --env host=http://localhost:5001 --env NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} --env token=${{ env.CYPRESS_LOGIN_TOKEN }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          PANDA_API_GW_URL: ${{ env.PANDA_API_GW_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_LOGIN_TOKEN: ${{ secrets.CYPRESS_LOGIN_TOKEN }}
          CYPRESS_host: http://localhost:5001
          CYPRESS_nextauth_secret: ${{ secrets.NEXTAUTH_SECRET }}
