name: Cypress Tests

on: [push]

defaults:
  run:
    working-directory: frontend/ui-main-app

jobs:
  cypress-run:
    runs-on: self-hosted
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.x.x # use the explicit version number
        with:
          # Specify Browser since container image is compile with Firefox
          browser: firefox         