name: Cypress all in one

on: [push]

defaults:
  run:
    working-directory: frontend/ui-main-app

jobs:
  build-run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.1
        with:
          build: yarn build
          start: yarn start
