name: Cypress test

on: [push]

defaults:
  run:
    working-directory: frontend/ui-main-app

jobs:
  build-run-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/ui-main-app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
      - run: yarn build
      - run: yarn cypress run --browser chrome --tag "chrome" --env host=http://localhost:5001
