name: Cypress test

on: [push]

defaults:
  run:
    working-directory: frontend/ui-main-app

jobs:
  build-run-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/ui-main-app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          install: false
          build: yarn build
          start: yarn start
          wait-on: "https://localhost:5001"
