name: Cypress all in one

on: [push]

defaults:
  run:
    working-directory: frontend/ui-main-app

jobs:
  build-run-test:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: frontend/ui-main-app
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker compose
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: docker-compose -f docker/cypress-all-in-container/docker-compose.yaml up --build
