name: Cypress test on pull request

on:
  - push

defaults:
  run:
    working-directory: frontend/ui-main-app
env:
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

jobs:
  build-run-test:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: frontend/ui-main-app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - run: npm run start &
      - run: node_modules/cypress/bin/cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --tag "chrome,${{ github.event.head_commit.author.name }},${{ github.event.head_commit.message }}"  --env host=http://localhost:5001
